/**
 * Project Ideas repository — CRUD against the `ideas` table.
 *
 * Section 4.6 fields. Ideas are submitted through the public portal
 * (Section 5.17), then reviewed and optionally promoted to projects by
 * an admin or project lead (Section 5.18).
 *
 * IDs are UUIDs generated by Postgres (`gen_random_uuid()` default on
 * the `idea_id` column).
 */

import type { IdeaId, ProjectIdea } from "./types";
import { getServiceRoleClient } from "@/lib/supabase/server";

const TABLE = "ideas" as const;

export type CreateIdeaInput = Omit<
  ProjectIdea,
  | "idea_id"
  | "submitted_at"
  | "status"
  | "admin_comments"
  | "converted_to_project_id"
  | "ai_overlap_analysis"
  | "edited_since_review"
  | "attachments"
> &
  Partial<
    Pick<
      ProjectIdea,
      "status" | "admin_comments" | "ai_overlap_analysis" | "attachments"
    >
  >;

export type UpdateIdeaInput = Partial<
  Omit<ProjectIdea, "idea_id" | "submitted_at">
>;

export const IdeaRepository = {
  async getAll(): Promise<ProjectIdea[]> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .order("submitted_at", { ascending: false });
    if (error) throw new Error(`ideas.getAll failed: ${error.message}`);
    return (data ?? []) as ProjectIdea[];
  },

  async getById(id: IdeaId): Promise<ProjectIdea | null> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .eq("idea_id", id)
      .maybeSingle();
    if (error) throw new Error(`ideas.getById failed: ${error.message}`);
    return (data as ProjectIdea | null) ?? null;
  },

  /**
   * Look up an idea by the SHA-256 hash of its edit token. Powers the
   * public, account-less "edit your idea" link. Returns null when no row
   * matches (invalid / stale link). Requires the `edit_token_hash` column
   * (migration 0013) — throws if it's absent, which is the correct signal
   * to the caller that the edit feature isn't provisioned yet.
   */
  async getByEditTokenHash(hash: string): Promise<ProjectIdea | null> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .eq("edit_token_hash", hash)
      .maybeSingle();
    if (error) {
      throw new Error(`ideas.getByEditTokenHash failed: ${error.message}`);
    }
    return (data as ProjectIdea | null) ?? null;
  },

  /**
   * Store the edit-token hash on an idea. Separate from `update` because
   * `edit_token_hash` is intentionally not part of the public `ProjectIdea`
   * shape (only its hash ever lives in the DB). Called best-effort at
   * submission time.
   */
  async setEditTokenHash(id: IdeaId, hash: string): Promise<void> {
    const { error } = await getServiceRoleClient()
      .from(TABLE)
      .update({ edit_token_hash: hash })
      .eq("idea_id", id);
    if (error) {
      throw new Error(`ideas.setEditTokenHash failed: ${error.message}`);
    }
  },

  async create(input: CreateIdeaInput): Promise<ProjectIdea> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .insert({
        submitter_name: input.submitter_name,
        submitter_email: input.submitter_email,
        idea_name: input.idea_name,
        description: input.description,
        urgency: input.urgency,
        requested_target_date: input.requested_target_date,
        key_stakeholders: input.key_stakeholders,
        status: input.status ?? "New",
        admin_comments: input.admin_comments ?? "",
        ai_overlap_analysis: input.ai_overlap_analysis ?? null,
        // submitted_at, idea_id, converted_to_project_id all have
        // sensible Postgres defaults.
      })
      .select()
      .single();
    if (error) throw new Error(`ideas.create failed: ${error.message}`);
    return data as ProjectIdea;
  },

  async update(id: IdeaId, patch: UpdateIdeaInput): Promise<ProjectIdea> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .update(patch)
      .eq("idea_id", id)
      .select()
      .single();
    if (error) throw new Error(`ideas.update failed: ${error.message}`);
    if (!data) throw new Error(`Idea ${id} not found`);
    return data as ProjectIdea;
  },

  async delete(id: IdeaId): Promise<void> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .delete()
      .eq("idea_id", id)
      .select("idea_id");
    if (error) throw new Error(`ideas.delete failed: ${error.message}`);
    if (!data || data.length === 0) throw new Error(`Idea ${id} not found`);
  },
};
