/**
 * Project repository — CRUD against the `projects` table.
 *
 * Section 4.1 fields. New project IDs (`YYYY-NNN`) are generated by
 * the Postgres function `next_project_id()` defined in the schema
 * migration; the importer that preserves legacy IDs passes them
 * explicitly (bypassing this repository — see
 * `scripts/migrate-to-supabase.ts`).
 *
 * `delete` prunes references to the deleted project from other
 * projects' `depends_on` and `dependencies` arrays so the dependency
 * graph never dangles. Cascading to tasks and decisions is handled
 * by the `ON DELETE CASCADE` foreign keys at the schema layer.
 */

import type { Project, ProjectId } from "./types";
import { getServiceRoleClient } from "@/lib/supabase/server";

const TABLE = "projects" as const;

/** Fields accepted by `create`. Auto-generated ones are excluded. */
export type CreateProjectInput = Omit<
  Project,
  | "project_id"
  | "date_added"
  | "updated_at"
  | "health_score"
  | "health_score_history"
  | "status_history"
> &
  Partial<
    Pick<Project, "health_score" | "health_score_history" | "status_history">
  >;

/** Fields accepted by `update`. ID and `date_added` are immutable. */
export type UpdateProjectInput = Partial<
  Omit<Project, "project_id" | "date_added" | "created_by">
>;

export const ProjectRepository = {
  async getAll(): Promise<Project[]> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*");
    if (error) throw new Error(`projects.getAll failed: ${error.message}`);
    return (data ?? []) as Project[];
  },

  async getById(id: ProjectId): Promise<Project | null> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .eq("project_id", id)
      .maybeSingle();
    if (error) throw new Error(`projects.getById failed: ${error.message}`);
    return (data as Project | null) ?? null;
  },

  async create(input: CreateProjectInput): Promise<Project> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .insert({
        name: input.name,
        description: input.description,
        application_product: input.application_product,
        project_type: input.project_type,
        priority: input.priority,
        status: input.status,
        phase: input.phase,
        primary_stakeholders: input.primary_stakeholders,
        project_lead: input.project_lead,
        additional_resources: input.additional_resources,
        resource_allocations: input.resource_allocations,
        target_date: input.target_date,
        ai_complexity_score: input.ai_complexity_score,
        ai_time_estimate: input.ai_time_estimate,
        roadmap_bucket: input.roadmap_bucket,
        roadmap_timeline_start: input.roadmap_timeline_start,
        github_issue_id: input.github_issue_id,
        jira_issue_id: input.jira_issue_id,
        depends_on: input.depends_on,
        dependencies: input.dependencies,
        external_dependencies: input.external_dependencies,
        document_links: input.document_links,
        custom_fields: input.custom_fields,
        created_by: input.created_by,
        health_score: input.health_score ?? null,
        health_score_history: input.health_score_history ?? [],
        status_history: input.status_history ?? [],
        // project_id, date_added, updated_at are filled by Postgres
        // defaults / triggers.
      })
      .select()
      .single();
    if (error) throw new Error(`projects.create failed: ${error.message}`);
    return data as Project;
  },

  async update(id: ProjectId, patch: UpdateProjectInput): Promise<Project> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .update(patch)
      .eq("project_id", id)
      .select()
      .single();
    if (error) throw new Error(`projects.update failed: ${error.message}`);
    if (!data) throw new Error(`Project ${id} not found`);
    return data as Project;
  },

  /**
   * Delete a project and prune any references to it from other
   * projects' dependency arrays. Throws if the project does not exist.
   *
   * Implemented as three queries because PostgREST doesn't expose a
   * transaction primitive — but the race is benign: a dangling
   * upstream_id is harmless (the dependency UI tolerates it) and the
   * cascade to tasks/decisions is handled by FK ON DELETE CASCADE at
   * the schema layer.
   *
   * If concurrent edits become a real risk, this can be wrapped in a
   * single Postgres function (created in a follow-up migration) and
   * called via `.rpc("delete_project", { p_id: id })`.
   */
  async delete(id: ProjectId): Promise<void> {
    const client = getServiceRoleClient();

    // 1. Find every project that depends on this one. We need the full
    //    rows so we can rewrite their `dependencies` jsonb arrays.
    const { data: dependents, error: depErr } = await client
      .from(TABLE)
      .select("project_id, depends_on, dependencies")
      .contains("depends_on", [id]);
    if (depErr)
      throw new Error(`projects.delete (find dependents) failed: ${depErr.message}`);

    // 2. Rewrite each dependent. We update one at a time because each
    //    has a different `dependencies` value; a bulk update wouldn't
    //    help.
    for (const row of dependents ?? []) {
      const newDependsOn = (row.depends_on as ProjectId[]).filter(
        (u) => u !== id,
      );
      const newDependencies = (
        row.dependencies as Array<{ upstream_id: ProjectId }>
      ).filter((d) => d.upstream_id !== id);
      const { error: updErr } = await client
        .from(TABLE)
        .update({
          depends_on: newDependsOn,
          dependencies: newDependencies,
        })
        .eq("project_id", row.project_id);
      if (updErr)
        throw new Error(
          `projects.delete (prune ${row.project_id}) failed: ${updErr.message}`,
        );
    }

    // 3. Finally, delete the target. Throw if it didn't exist so the
    //    caller's error handling sees the same shape as the JSON era.
    const { data, error } = await client
      .from(TABLE)
      .delete()
      .eq("project_id", id)
      .select("project_id");
    if (error) throw new Error(`projects.delete failed: ${error.message}`);
    if (!data || data.length === 0) {
      throw new Error(`Project ${id} not found`);
    }
  },
};
