/**
 * Task repository — CRUD against the `tasks` table.
 *
 * Section 4.2 fields. New task IDs (`YY-NNNN`) are generated by the
 * Postgres function `next_task_id()` defined in the schema migration;
 * importers that need to preserve legacy IDs pass them explicitly via
 * the migration script (which bypasses this repository).
 *
 * `delete` is scoped to a single task. Bulk deletion when a parent
 * project is removed happens automatically via the `ON DELETE CASCADE`
 * foreign key on `tasks.project_id`.
 */

import type { ProjectId, Task, TaskId } from "./types";
import { getServiceRoleClient } from "@/lib/supabase/server";

const TABLE = "tasks" as const;

export type CreateTaskInput = Omit<
  Task,
  "task_id" | "created_at" | "updated_at" | "comment_history" | "estimate_hours"
> &
  Partial<Pick<Task, "comment_history" | "estimate_hours">>;

export type UpdateTaskInput = Partial<
  Omit<Task, "task_id" | "project_id" | "created_at">
>;

export const TaskRepository = {
  async getAll(): Promise<Task[]> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*");
    if (error) throw new Error(`tasks.getAll failed: ${error.message}`);
    return (data ?? []) as Task[];
  },

  async getById(id: TaskId): Promise<Task | null> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .eq("task_id", id)
      .maybeSingle();
    if (error) throw new Error(`tasks.getById failed: ${error.message}`);
    return (data as Task | null) ?? null;
  },

  /** Convenience accessor — every Tasks page needs to filter by project. */
  async getByProjectId(projectId: ProjectId): Promise<Task[]> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .select("*")
      .eq("project_id", projectId);
    if (error) throw new Error(`tasks.getByProjectId failed: ${error.message}`);
    return (data ?? []) as Task[];
  },

  async create(input: CreateTaskInput): Promise<Task> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .insert({
        project_id: input.project_id,
        task_name: input.task_name,
        detailed_description: input.detailed_description,
        status: input.status,
        priority: input.priority,
        responsible: input.responsible,
        additional_assignees: input.additional_assignees,
        target_date: input.target_date,
        blocked: input.blocked,
        blocker_issue_task: input.blocker_issue_task,
        blocker_type: input.blocker_type,
        blocker_task_id: input.blocker_task_id,
        blocker_project_id: input.blocker_project_id,
        comments: input.comments,
        document_links: input.document_links,
        template_id: input.template_id,
        comment_history: input.comment_history ?? [],
        estimate_hours: input.estimate_hours ?? null,
        // task_id, created_at, updated_at are filled by Postgres defaults
      })
      .select()
      .single();
    if (error) throw new Error(`tasks.create failed: ${error.message}`);
    return data as Task;
  },

  async update(id: TaskId, patch: UpdateTaskInput): Promise<Task> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .update(patch)
      .eq("task_id", id)
      .select()
      .single();
    if (error) throw new Error(`tasks.update failed: ${error.message}`);
    if (!data) throw new Error(`Task ${id} not found`);
    return data as Task;
  },

  async delete(id: TaskId): Promise<void> {
    const { data, error } = await getServiceRoleClient()
      .from(TABLE)
      .delete()
      .eq("task_id", id)
      .select("task_id");
    if (error) throw new Error(`tasks.delete failed: ${error.message}`);
    if (!data || data.length === 0) throw new Error(`Task ${id} not found`);
  },
};
