/**
 * Refresh projects, tasks, and ideas in Supabase from the latest
 * spreadsheet snapshot — without touching anything else.
 *
 *   # 1. Refresh data/*.json from the source spreadsheet first
 *   npm run seed
 *
 *   # 2. Dry-run to see what would change
 *   npm run import:spreadsheet
 *
 *   # 3. Write the changes
 *   npm run import:spreadsheet -- --confirm
 *
 * What gets touched:
 *
 *   - **projects** — UPSERT by `project_id` (stable across seed runs).
 *     New rows: inserted with the full seed-default shape.
 *     Existing rows: only the spreadsheet-sourced columns are
 *     updated; app-owned fields (AI scores, health score and
 *     history, status history, dependencies, document links,
 *     resource allocations, custom fields) are preserved untouched.
 *   - **tasks** — UPSERT by `task_id`, same logic. App-owned fields
 *     (comment history, blocker_type, document_links) are preserved.
 *   - **ideas** — full wipe + reinsert. Idea UUIDs are generated by
 *     `seed` and aren't stable across runs, so there's no key to
 *     upsert against. The audit log retains its entries; their
 *     idea_id references just become orphaned, which the audit page
 *     already handles gracefully.
 *
 * What stays untouched:
 *
 *   - users, audit_log, decisions, notifications, templates, settings
 *   - app-state on existing projects/tasks (AI fields, health, history)
 *   - projects/tasks that exist in Supabase but NOT in the spreadsheet
 *     (additive sync — manual additions in the app survive)
 *
 * Idempotent: re-run any time after `seed`. Same end state.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import type {
  Project,
  ProjectIdea,
  Task,
} from "../lib/db/types";

// ---------------------------------------------------------------------------
// Paths + env
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");
const DATA_DIR = process.env.IIM_DATA_DIR ?? path.join(REPO_ROOT, "data");

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

function bail(message: string): never {
  console.error(`✗ ${message}`);
  process.exit(1);
}

if (!url) bail("NEXT_PUBLIC_SUPABASE_URL is not set in .env.local.");
if (!serviceKey) bail("SUPABASE_SERVICE_ROLE_KEY is not set in .env.local.");

const confirm = process.argv.includes("--confirm");

// ---------------------------------------------------------------------------
// Spreadsheet-sourced field lists
// ---------------------------------------------------------------------------
//
// Only these columns get UPDATED on existing rows. Anything not in
// these lists was either (a) set by `seed` as a default the
// spreadsheet doesn't carry, or (b) populated by app activity (AI
// estimates, health recalcs, dependency edits). Leaving them alone
// preserves real user work.

const PROJECT_SHEET_FIELDS: ReadonlyArray<keyof Project> = [
  "name",
  "description",
  "application_product",
  "project_type",
  "date_added",
  "priority",
  "status",
  "phase",
  "primary_stakeholders",
  "project_lead",
  "additional_resources",
  "target_date",
];

const TASK_SHEET_FIELDS: ReadonlyArray<keyof Task> = [
  "project_id",
  "task_name",
  "detailed_description",
  "status",
  "priority",
  "responsible",
  "target_date",
  "blocked",
  "blocker_issue_task",
  "comments",
  "estimate_hours",
];

// ---------------------------------------------------------------------------
// Load JSON
// ---------------------------------------------------------------------------

function loadArray<T>(name: string): T[] {
  const file = path.join(DATA_DIR, name);
  try {
    const parsed = JSON.parse(readFileSync(file, "utf8"));
    if (!Array.isArray(parsed)) {
      console.warn(`  ⚠ ${name} is not an array — treating as empty.`);
      return [];
    }
    return parsed as T[];
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      bail(
        `${name} not found in ${DATA_DIR}. ` +
          "Run `npm run seed` first to regenerate the JSON snapshots.",
      );
    }
    throw err;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const BATCH = 200;

async function bulkInsert(
  client: SupabaseClient,
  table: string,
  rows: readonly unknown[],
): Promise<void> {
  if (rows.length === 0) return;
  for (let i = 0; i < rows.length; i += BATCH) {
    const slice = rows.slice(i, i + BATCH);
    // PostgREST's typed builder narrows insert payloads against a
    // generated Database schema we don't have; the type at this
    // boundary is correctly `any`.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { error } = await client.from(table).insert(slice as any);
    if (error) {
      bail(
        `Insert into ${table} failed at rows ${i + 1}-${i + slice.length}: ${error.message}`,
      );
    }
  }
}

/**
 * Pull a subset of fields off `source` keyed by `fields`. Used to
 * build a sparse UPDATE payload that contains only the
 * spreadsheet-sourced columns. Skips undefined values so partial
 * rows (e.g. a missing target_date) don't overwrite existing
 * values with null.
 */
function pickSheetFields<T extends Record<string, unknown>>(
  source: T,
  fields: ReadonlyArray<keyof T>,
): Partial<T> {
  const out: Partial<T> = {};
  for (const f of fields) {
    if (source[f] !== undefined) out[f] = source[f];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

async function syncProjects(
  client: SupabaseClient,
  projects: Project[],
): Promise<{ inserted: number; updated: number }> {
  if (projects.length === 0) return { inserted: 0, updated: 0 };

  // Which project_ids already exist? Need this to partition into
  // INSERT vs UPDATE. `select.in()` caps at the network payload
  // size; chunk so very large imports don't trip the URL limit.
  const existing = new Set<string>();
  for (let i = 0; i < projects.length; i += BATCH) {
    const slice = projects.slice(i, i + BATCH).map((p) => p.project_id);
    const { data, error } = await client
      .from("projects")
      .select("project_id")
      .in("project_id", slice);
    if (error) bail(`projects existence check failed: ${error.message}`);
    for (const row of data ?? []) {
      existing.add((row as { project_id: string }).project_id);
    }
  }

  const toInsert = projects.filter((p) => !existing.has(p.project_id));
  const toUpdate = projects.filter((p) => existing.has(p.project_id));

  // New projects: full record from the JSON (which already includes
  // sensible defaults for app-owned fields).
  if (toInsert.length > 0) {
    await bulkInsert(client, "projects", toInsert);
  }

  // Existing projects: patch only the spreadsheet-sourced fields.
  for (const project of toUpdate) {
    const patch = pickSheetFields(
      project as unknown as Record<string, unknown>,
      PROJECT_SHEET_FIELDS as readonly string[],
    );
    const { error } = await client
      .from("projects")
      .update(patch)
      .eq("project_id", project.project_id);
    if (error) {
      bail(
        `projects update for ${project.project_id} failed: ${error.message}`,
      );
    }
  }

  return { inserted: toInsert.length, updated: toUpdate.length };
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

async function syncTasks(
  client: SupabaseClient,
  tasks: Task[],
): Promise<{ inserted: number; updated: number }> {
  if (tasks.length === 0) return { inserted: 0, updated: 0 };

  const existing = new Set<string>();
  for (let i = 0; i < tasks.length; i += BATCH) {
    const slice = tasks.slice(i, i + BATCH).map((t) => t.task_id);
    const { data, error } = await client
      .from("tasks")
      .select("task_id")
      .in("task_id", slice);
    if (error) bail(`tasks existence check failed: ${error.message}`);
    for (const row of data ?? []) {
      existing.add((row as { task_id: string }).task_id);
    }
  }

  const toInsert = tasks.filter((t) => !existing.has(t.task_id));
  const toUpdate = tasks.filter((t) => existing.has(t.task_id));

  if (toInsert.length > 0) {
    await bulkInsert(client, "tasks", toInsert);
  }

  for (const task of toUpdate) {
    const patch = pickSheetFields(
      task as unknown as Record<string, unknown>,
      TASK_SHEET_FIELDS as readonly string[],
    );
    const { error } = await client
      .from("tasks")
      .update(patch)
      .eq("task_id", task.task_id);
    if (error) {
      bail(`tasks update for ${task.task_id} failed: ${error.message}`);
    }
  }

  return { inserted: toInsert.length, updated: toUpdate.length };
}

// ---------------------------------------------------------------------------
// Ideas
// ---------------------------------------------------------------------------

async function syncIdeas(
  client: SupabaseClient,
  ideas: ProjectIdea[],
): Promise<{ wiped: number; inserted: number }> {
  // Wipe first. PostgREST requires a non-null filter on delete; we
  // use `not idea_id is null`, which matches every row.
  const { data: deleted, error: delErr } = await client
    .from("ideas")
    .delete()
    .not("idea_id", "is", null)
    .select("idea_id");
  if (delErr) bail(`ideas wipe failed: ${delErr.message}`);

  if (ideas.length > 0) {
    await bulkInsert(client, "ideas", ideas);
  }

  return { wiped: deleted?.length ?? 0, inserted: ideas.length };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log(`Source:      ${DATA_DIR}`);
  console.log(`Destination: ${url}`);
  console.log(`Mode:        ${confirm ? "WRITE (--confirm)" : "dry run"}`);
  console.log("");

  const projects = loadArray<Project>("projects.json");
  const tasks = loadArray<Task>("tasks.json");
  const ideas = loadArray<ProjectIdea>("ideas.json");

  console.log("Source counts:");
  console.log(`  projects.json   ${projects.length}`);
  console.log(`  tasks.json      ${tasks.length}`);
  console.log(`  ideas.json      ${ideas.length}`);
  console.log("");

  const client = createClient(url!, serviceKey!, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // -------------------------------------------------------------------------
  // Pre-flight: report what's already in Supabase so the dry run
  // shows new-vs-update split before we write anything.
  // -------------------------------------------------------------------------

  if (!confirm) {
    const sampleProjectIds = projects.map((p) => p.project_id);
    const sampleTaskIds = tasks.map((t) => t.task_id);
    const existingProjects = new Set<string>();
    const existingTasks = new Set<string>();
    for (let i = 0; i < sampleProjectIds.length; i += BATCH) {
      const slice = sampleProjectIds.slice(i, i + BATCH);
      const { data } = await client
        .from("projects")
        .select("project_id")
        .in("project_id", slice);
      for (const row of data ?? []) {
        existingProjects.add((row as { project_id: string }).project_id);
      }
    }
    for (let i = 0; i < sampleTaskIds.length; i += BATCH) {
      const slice = sampleTaskIds.slice(i, i + BATCH);
      const { data } = await client
        .from("tasks")
        .select("task_id")
        .in("task_id", slice);
      for (const row of data ?? []) {
        existingTasks.add((row as { task_id: string }).task_id);
      }
    }
    const { count: existingIdeaCount } = await client
      .from("ideas")
      .select("idea_id", { count: "exact", head: true });

    const projectsNew = projects.filter((p) => !existingProjects.has(p.project_id)).length;
    const projectsExisting = projects.length - projectsNew;
    const tasksNew = tasks.filter((t) => !existingTasks.has(t.task_id)).length;
    const tasksExisting = tasks.length - tasksNew;

    console.log("Plan (dry run):");
    console.log(
      `  projects   →   insert ${projectsNew}, update ${projectsExisting} (only spreadsheet fields)`,
    );
    console.log(
      `  tasks      →   insert ${tasksNew}, update ${tasksExisting} (only spreadsheet fields)`,
    );
    console.log(
      `  ideas      →   wipe ${existingIdeaCount ?? 0}, insert ${ideas.length}`,
    );
    console.log("");
    console.log(
      "Re-run with --confirm to apply. Nothing else (users, audit log,",
    );
    console.log("decisions, notifications, templates, settings) will be touched.");
    return;
  }

  // -------------------------------------------------------------------------
  // Write phase
  // -------------------------------------------------------------------------

  console.log("Syncing projects…");
  const p = await syncProjects(client, projects);
  console.log(
    `  ✓ projects: inserted ${p.inserted}, updated ${p.updated} (only spreadsheet fields)`,
  );

  console.log("Syncing tasks…");
  const t = await syncTasks(client, tasks);
  console.log(
    `  ✓ tasks: inserted ${t.inserted}, updated ${t.updated} (only spreadsheet fields)`,
  );

  console.log("Syncing ideas (wipe + reinsert)…");
  const i = await syncIdeas(client, ideas);
  console.log(`  ✓ ideas: wiped ${i.wiped}, inserted ${i.inserted}`);

  console.log("");
  console.log("Import complete. Untouched: users, audit_log, decisions,");
  console.log("notifications, templates, settings — and any app-owned fields");
  console.log("on existing projects/tasks (AI scores, health, history, etc.).");
}

main().catch((err) => {
  console.error("✗ Unexpected error:", err);
  process.exit(1);
});
