-- =============================================================================
-- Praxis initial schema — Stage 1 of the JSON → Supabase migration.
-- =============================================================================
--
-- Mirrors the TypeScript interfaces in lib/db/types.ts. Column names match
-- the JSON field names exactly so PostgREST round-trips cleanly without an
-- ORM mapping layer.
--
-- Design notes:
--
--   * ID format preserved from the file-store era. Projects are YYYY-NNN,
--     tasks are YY-NNNN, everything else is UUID. The two non-UUID
--     formats are generated by Postgres functions defined below so the
--     repositories can rely on database-side atomicity rather than a
--     per-file mutex.
--   * Arrays of primitives → text[]. Arrays of objects → jsonb. We do
--     NOT explode embedded shapes (status_history, document_links,
--     dependencies, etc.) into their own tables — the application
--     treats them as opaque blobs hung off a parent record, and JSONB
--     is the cleanest match.
--   * Foreign keys are intentionally minimal. Only the strong
--     parent-child relationships get them (tasks→projects,
--     decisions→projects). Soft references to users (created_by,
--     responsible, actor_id, made_by) stay loose: those columns hold
--     a mix of UUIDs and free-text names in the legacy data, and we
--     don't want a stray legacy "Josh" to fail a constraint.
--   * RLS is enabled on every table but no policies are written. The
--     application uses the service-role key on the server, which
--     bypasses RLS — auth enforcement lives in our service layer
--     (requirePermission). When Stage 2 lands and the browser starts
--     talking to Supabase directly, we'll add per-table policies for
--     the authenticated and anon roles.
--   * Stage 1 keeps the legacy `users` table with password_hash,
--     invite_token, etc. — NextAuth is still the auth surface, just
--     reading from Postgres instead of users.json. Stage 2 splits
--     that into auth.users + profiles.

-- =============================================================================
-- Helpers
-- =============================================================================

-- Auto-update updated_at on every UPDATE. Applied via trigger to each
-- table that has an updated_at column.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Atomic generator for the YYYY-NNN project ID convention.
-- pg_advisory_xact_lock keyed by year serializes concurrent inserts
-- inside the same year, eliminating the duplicate-key race the JSON
-- store's per-file mutex used to handle. The lock is released
-- automatically at transaction commit.
create or replace function public.next_project_id()
returns text
language plpgsql
as $$
declare
  yr text := to_char(current_date, 'YYYY');
  next_n integer;
  lock_key bigint := hashtext('next_project_id_' || yr);
begin
  perform pg_advisory_xact_lock(lock_key);
  select coalesce(max(substring(project_id from 6)::integer), 0) + 1
    into next_n
    from public.projects
   where project_id like yr || '-%'
     and substring(project_id from 6) ~ '^\d+$';
  return yr || '-' || lpad(next_n::text, 3, '0');
end;
$$;

-- Atomic generator for the YY-NNNN task ID convention. Same pattern
-- as next_project_id but with a 2-digit year and 4-digit suffix.
create or replace function public.next_task_id()
returns text
language plpgsql
as $$
declare
  yy text := to_char(current_date, 'YY');
  next_n integer;
  lock_key bigint := hashtext('next_task_id_' || yy);
begin
  perform pg_advisory_xact_lock(lock_key);
  select coalesce(max(substring(task_id from 4)::integer), 0) + 1
    into next_n
    from public.tasks
   where task_id like yy || '-%'
     and substring(task_id from 4) ~ '^\d+$';
  return yy || '-' || lpad(next_n::text, 4, '0');
end;
$$;

-- =============================================================================
-- users
-- =============================================================================
-- Stage 1 mirrors the existing User type 1:1. Stage 2 will split
-- identity (email/password/tokens) into auth.users and the rest into a
-- profiles table.

create table public.users (
  user_id                            uuid primary key default gen_random_uuid(),
  email                              text unique not null,
  name                               text not null,
  role                               text not null
    check (role in ('Admin', 'Project Lead', 'Team Member', 'Viewer')),
  password_hash                      text not null default '',
  active                             boolean not null default true,
  invite_token                       text,
  invite_token_expires_at            timestamptz,
  password_reset_token               text,
  password_reset_token_expires_at    timestamptz,
  notification_preferences           jsonb not null default '{}'::jsonb,
  digest_mode                        boolean not null default false,
  created_at                         timestamptz not null default now(),
  updated_at                         timestamptz not null default now()
);

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

create index users_email_lower_idx on public.users (lower(email));
create index users_role_idx on public.users (role);
create index users_active_idx on public.users (active);

-- =============================================================================
-- projects
-- =============================================================================

create table public.projects (
  project_id                  text primary key default public.next_project_id(),
  name                        text not null,
  description                 text not null default '',
  application_product         text not null default '',
  project_type                text not null,
  date_added                  date not null default current_date,
  priority                    text not null,
  status                      text not null,
  phase                       text not null,
  primary_stakeholders        text[] not null default '{}',
  project_lead                text not null default '',
  additional_resources        text[] not null default '{}',
  resource_allocations        jsonb not null default '{}'::jsonb,
  target_date                 date,
  ai_complexity_score         text
    check (ai_complexity_score is null
        or ai_complexity_score in ('Low', 'Medium', 'High', 'Very High')),
  ai_time_estimate            text,
  roadmap_bucket              text,
  roadmap_timeline_start      date,
  github_issue_id             text,
  jira_issue_id               text,
  health_score                text
    check (health_score is null
        or health_score in ('Red', 'Yellow', 'Green')),
  health_score_history        jsonb not null default '[]'::jsonb,
  status_history              jsonb not null default '[]'::jsonb,
  depends_on                  text[] not null default '{}',
  dependencies                jsonb not null default '[]'::jsonb,
  document_links              jsonb not null default '[]'::jsonb,
  custom_fields               jsonb not null default '{}'::jsonb,
  created_by                  text not null default '',
  updated_at                  timestamptz not null default now()
);

create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

create index projects_status_idx on public.projects (status);
create index projects_date_added_idx on public.projects (date_added desc);
create index projects_created_by_idx on public.projects (created_by);
create index projects_project_lead_idx on public.projects (project_lead);
create index projects_health_idx on public.projects (health_score);

-- =============================================================================
-- tasks
-- =============================================================================

create table public.tasks (
  task_id                  text primary key default public.next_task_id(),
  project_id               text not null
                             references public.projects(project_id) on delete cascade,
  task_name                text not null,
  detailed_description     text not null default '',
  status                   text not null
    check (status in ('Not Started', 'In Progress', 'Blocked', 'Delayed',
                      'On Hold', 'Complete', 'Canceled')),
  priority                 text not null,
  responsible              text not null default '',
  additional_assignees     text[] not null default '{}',
  target_date              date,
  blocked                  boolean not null default false,
  blocker_issue_task       text not null default '',
  blocker_type             text
    check (blocker_type is null or blocker_type in ('task', 'project', 'other')),
  blocker_task_id          text,
  blocker_project_id       text,
  comments                 text not null default '',
  comment_history          jsonb not null default '[]'::jsonb,
  document_links           jsonb not null default '[]'::jsonb,
  estimate_hours           numeric(6,2),
  template_id              uuid,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

create trigger tasks_set_updated_at
  before update on public.tasks
  for each row execute function public.set_updated_at();

create index tasks_project_id_idx on public.tasks (project_id);
create index tasks_responsible_idx on public.tasks (responsible);
create index tasks_status_idx on public.tasks (status);
create index tasks_target_date_idx on public.tasks (target_date);

-- =============================================================================
-- ideas (public submissions queue)
-- =============================================================================

create table public.ideas (
  idea_id                    uuid primary key default gen_random_uuid(),
  submitter_name             text not null,
  submitter_email            text,
  idea_name                  text not null,
  description                text not null,
  urgency                    text not null
    check (urgency in ('Low', 'Medium', 'High', 'Critical')),
  requested_target_date      date,
  key_stakeholders           text not null default '',
  submitted_at               timestamptz not null default now(),
  status                     text not null default 'New'
    check (status in ('New', 'Under Review', 'Approved', 'Rejected', 'Converted')),
  admin_comments             text not null default '',
  converted_to_project_id    text,
  ai_overlap_analysis        text
);

create index ideas_status_idx on public.ideas (status);
create index ideas_submitted_at_idx on public.ideas (submitted_at desc);

-- =============================================================================
-- decisions (per-project decision log, append-only)
-- =============================================================================

create table public.decisions (
  entry_id           uuid primary key default gen_random_uuid(),
  project_id         text not null
                       references public.projects(project_id) on delete cascade,
  entry_date         date not null default current_date,
  decision_summary   text not null,
  rationale          text not null,
  made_by            text not null default '',
  decision_type      text not null
    check (decision_type in ('Scope Change', 'Priority Change', 'Timeline Change',
                             'Resource Change', 'Technical Decision', 'Other')),
  created_at         timestamptz not null default now()
);

create index decisions_project_id_idx on public.decisions (project_id);
create index decisions_entry_date_idx on public.decisions (entry_date desc);

-- =============================================================================
-- notifications
-- =============================================================================

create table public.notifications (
  notification_id   uuid primary key default gen_random_uuid(),
  user_id           uuid not null,
  type              text not null
    check (type in ('TaskAssigned', 'TaskDueSoon', 'TaskOverdue', 'ProjectBlocked',
                    'DependencyBlocked', 'HealthScoreChanged', 'IdeaStatusChanged')),
  message           text not null,
  entity_type       text not null
    check (entity_type in ('Project', 'Task', 'Idea')),
  entity_id         text not null,
  read              boolean not null default false,
  created_at        timestamptz not null default now()
);

create index notifications_user_id_idx on public.notifications (user_id);
create index notifications_user_read_idx on public.notifications (user_id, read);
create index notifications_created_at_idx on public.notifications (created_at desc);

-- =============================================================================
-- templates (task templates)
-- =============================================================================

create table public.templates (
  template_id     uuid primary key default gen_random_uuid(),
  template_name   text not null,
  project_type    text not null,
  tasks           jsonb not null default '[]'::jsonb,
  created_by      text not null default ''
);

create index templates_project_type_idx on public.templates (project_type);

-- =============================================================================
-- audit_log (append-only)
-- =============================================================================

create table public.audit_log (
  entry_id        uuid primary key default gen_random_uuid(),
  occurred_at     timestamptz not null default now(),
  actor_id        uuid,
  actor_name      text,
  entity_type     text not null
    check (entity_type in ('Project', 'Task', 'Idea', 'User', 'Decision',
                           'Template', 'Settings')),
  entity_id       text not null,
  entity_label    text not null,
  action          text not null
    check (action in ('create', 'update', 'delete', 'status_change', 'convert',
                      'invite', 'deactivate', 'activate', 'role_change',
                      'password_reset')),
  summary         text not null
);

create index audit_log_occurred_at_idx on public.audit_log (occurred_at desc);
create index audit_log_entity_idx on public.audit_log (entity_type, entity_id);
create index audit_log_actor_id_idx on public.audit_log (actor_id);
create index audit_log_action_idx on public.audit_log (action);

-- =============================================================================
-- settings (singleton)
-- =============================================================================
--
-- One row, id='singleton'. The CHECK constraint prevents accidental
-- additional inserts. The application reads with `.eq('id', 'singleton')`
-- and upserts with the same key.

create table public.settings (
  id                          text primary key default 'singleton'
                                check (id = 'singleton'),
  health_score_thresholds     jsonb not null,
  branding                    jsonb not null,
  notification_defaults       jsonb not null,
  custom_field_definitions    jsonb not null default '[]'::jsonb,
  kanban_configs              jsonb not null default '[]'::jsonb,
  role_permissions            jsonb not null,
  enum_extensions             jsonb not null,
  resource_settings           jsonb not null,
  portfolio_quadrants         jsonb not null
);

-- =============================================================================
-- Row-Level Security
-- =============================================================================
--
-- Enable RLS on every public table. No policies = deny-by-default for
-- anon and authenticated roles. The service-role key bypasses RLS, so
-- server-side code continues to work. We'll layer policies on in Stage
-- 2 when the browser starts hitting Supabase directly for auth flows
-- and (eventually) the public /submit idea form.

alter table public.users         enable row level security;
alter table public.projects      enable row level security;
alter table public.tasks         enable row level security;
alter table public.ideas         enable row level security;
alter table public.decisions     enable row level security;
alter table public.notifications enable row level security;
alter table public.templates     enable row level security;
alter table public.audit_log     enable row level security;
alter table public.settings      enable row level security;
